name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "production" ]

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: |
          echo "PROJECT_ID : ${{ vars.PROJECT_ID }}"
          echo "SA : ${{ secrets.SERVICE_ACCOUNTS }}"
