name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "production" ]

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: |
          echo "PROJECT_ID : ${{ env.PROJECT_ID }} ${{ vars.PROJECT_ID }}"
          echo "env var : $env_var"
