name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      service:
        type: string
        required: true
      region:
        type: string
        required: true
      image:
        type: string
        required: true

    secrets:
      gcp_credentials:
        required: true


jobs:
  cloud-run:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Generate Cloud Run Service
        run: |-
          echo ${{ inputs.service }}
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
        # credentials_json: '${{ secrets.gcp_credentials }}'
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS }}'
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          # service: ${{ inputs.service }}
          # region: ${{ inputs.region }}
          # image: ${{ inputs.image }}
        service: ${{ vars.SERVICE }}
        region: ${{ vars.REGION }}
        image: ${{ vars.IMAGE_REGISTRY }}/${{ vars.PROJECT_ID }}/${{ vars.SERVICE }}:${{ github.sha }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}