name: Deploy

on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      region:
        type: string
        required: true
      image:
        type: string
        required: true

    secrets:
      gcp_credentials:
        required: true


jobs:
  cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Cloud Run Service
        run: |-
          echo ${{ inputs.service }}
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.service }}
          region: ${{ inputs.region }}
          image: ${{ inputs.image }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}